name: Ekstrak jwpSources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Setiap 2 jam

jobs:
  ekstrak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v4

      - name: Ambil page_url.txt dari repo privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/page_url.txt $HOME/page_url.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests

      - name: Jalankan skrip ekstraksi
        run: |
          python ekstrak.py

      - name: Debug - Status Perubahan Git
        run: |
          echo "📁 File .txt yang tersedia:"
          ls -lah *.txt || echo "Tidak ada file .txt"

          echo "🔍 Status Git:"
          git status

          echo "🔍 Perubahan yang distaging:"
          git diff --cached || echo "(tidak ada perubahan)"

          echo "🔍 Perubahan di working directory:"
          git diff || echo "(tidak ada perubahan)"

      - name: Commit hasil ke repo publik
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Set remote agar bisa push
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          # Tambahkan file hasil ekstrak
          git add jajan_kuekue.json

          # Commit jika ada perubahan
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan, tidak perlu commit."
          else
            git commit -m "Update Widevine DRM info"
            git push origin master || echo "⚠️ Push gagal"
          fi
