name: Ekstrak jwpSources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # setiap 2 jam

jobs:
  ekstrak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v4

      - name: Ambil page_url.txt dari repo privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/page_url.txt $HOME/page_url.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python ekstrak.py

      # Opsional: commit hasil jika perlu simpan ke repo publik
      - name: Commit hasil widevine.json
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add jajan_kuekue.txt

          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan, tidak perlu commit."
          else
            git commit -m "Update Widevine DRM info"
            git push
          fi
