name: Ekstrak jwpSources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: commit-to-master
  cancel-in-progress: false

jobs:
  ekstrak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/page_url.txt $HOME/page_url.txt

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install requests
      - run: python ekstrak.py

      - name: Commit hasil
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          if ! git diff --quiet jajan_kuekue.json; then
            git add jajan_kuekue.json
            git commit -m "Update Widevine DRM info - $(date '+%Y-%m-%d %H:%M:%S')"
            git fetch origin
            git pull --rebase origin master || exit 1
            git push origin master || echo "⚠️ Push gagal"
          else
            echo "✅ Tidak ada perubahan"
          fi
