name: Get Twitch M3U8 URL and Commit

on:
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install streamlink
        run: |
          sudo apt update
          sudo apt install -y streamlink

      - name: Jalankan script Python
        run: python get_twitch_url.py

      - name: Commit dan Push hasil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *.txt
          git commit -m "Update Twitch M3U8 URL"
          git push
