name: Post Jadwal ke Telegram

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v3

      - name: Clone repo privat berisi botdata.txt
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/botdata.txt $HOME/botdata.txt
        env:
          TOKEN_PRIVATE: ${{ secrets.TOKEN_PRIVATE }}
          REPO_PRIVATE: ${{ secrets.REPO_PRIVATE }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests python-telegram-bot==20.7

      - name: Jalankan bot autopost
        run: python autopost.py
