name: Jalankan Bash2 Python untuk M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Setiap 10 menit

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo publik
      - name: Checkout Repo Publik
        uses: actions/checkout@v4

      # 2. Install dependensi
      - name: Install yt-dlp dan Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install -U yt-dlp

      # 3. Clone repo privat (untuk ambil cookies & urls_live.txt)
      - name: Ambil cookies.txt dan urls_live.txt dari repo privat
        run: |
          git clone https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/cookies.txt $HOME/cookies.txt
          cp private/urls_live.txt $HOME/urls_live.txt

      # 4. Jalankan bash2.py
      - name: Jalankan bash2.py
        run: |
          python3 bash2.py

      # 5. Commit dan Push hasil (jika ada)
      - name: Commit dan Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "Tidak ada perubahan"
          else
            git commit -m "Update dari ${GITHUB_REPOSITORY}/bash2.py - $(date '+%Y-%m-%d %H:%M:%S')"
            git fetch origin master
            git merge --strategy=ours origin/master || true
            git push origin master || echo "Push gagal"
          fi
