name: Semua Workflow Gabungan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Setiap 1 jam
    - cron: '0 */4 * * *'  # Untuk YML5 setiap 4 jam

jobs:
  ekstrak_jwpSources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ambil page_url.txt dari repo privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/page_url.txt $HOME/page_url.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Jalankan skrip ekstraksi
        run: python ekstrak.py

      - name: Commit hasil
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "Terakhir dijalankan pada: $(date '+%Y-%m-%d %H:%M:%S')" > .last_run_marker
          git add jajan_kuekue.json .last_run_marker
          git fetch origin
          git pull --rebase origin master || exit 1
          git commit -m "Update jwpSources - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ Tidak ada perubahan"
          git push origin master || echo "⚠️ Push gagal"

  twitch_m3u8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & streamlink
        run: |
          sudo apt update
          sudo apt install -y streamlink
          pip install requests

      - name: Ambil channel.txt
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/channel.txt $HOME/channel.txt

      - name: Jalankan Python
        run: python pesawatsry.py

      - name: Commit dan Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Terakhir dijalankan pada: $(date '+%Y-%m-%d %H:%M:%S')" > .last_run_marker
          git add -u
          git add .last_run_marker
          git commit -m "Update Twitch M3U8 URL - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ Tidak ada perubahan"
          git pull --rebase origin master || true
          git push origin master || echo "⚠️ Push gagal"

  grab_tesst7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Ambil daylidata.txt
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} temp_private
          cp temp_private/daylidata.txt $HOME/daylidata.txt
          rm -rf temp_private

      - name: Jalankan getdaily.py
        run: python getdaily.py

      - name: Commit dan Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          echo "Terakhir dijalankan pada: $(date '+%Y-%m-%d %H:%M:%S')" > .last_run_marker
          git add TESSTSS7.m3u8 .last_run_marker
          git pull --rebase --autostash origin master
          git commit -m "auto: update TESSTSS7.m3u8 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ Tidak ada perubahan"
          git push origin master || echo "⚠️ Push gagal"

  run_bash2_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp dan jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install -U yt-dlp

      - name: Ambil cookies & URL dari repo privat
        run: |
          git clone https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/cookies.txt $HOME/cookies.txt
          cp private/urls_live.txt $HOME/urls_live.txt

      - name: Jalankan bash2.py
        run: python3 bash2.py

      - name: Commit dan Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "Terakhir dijalankan pada: $(date '+%Y-%m-%d %H:%M:%S')" > .last_run_marker
          git add . .last_run_marker
          git pull --rebase origin master || true
          git commit -m "Update dari bash2.py - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ Tidak ada perubahan"
          git push origin master || echo "⚠️ Push gagal"

  run_bash1_sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yt-dlp dan jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install -U yt-dlp
          mkdir -p out

      - name: Ambil file privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} private
          cp private/cookies.txt $HOME/cookies2.txt || true
          cp private/urls.txt $HOME/urls.txt || true

      - name: Jalankan bash1.sh
        run: |
          chmod +x bash1.sh
          ./bash1.sh

      - name: Commit dan Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin
          git pull --rebase origin master || exit 1
          echo "Terakhir dijalankan pada: $(date '+%Y-%m-%d %H:%M:%S')" > .last_run_marker
          find . -name "*.txt" -not -path "./private/*" -exec git add {} +
          git add .last_run_marker
          git commit -m "Update otomatis via bash1.sh - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ Tidak ada perubahan"
          git push origin master || echo "⚠️ Push gagal"
