name: Video URL Fetcher

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam pada menit ke-0
  workflow_dispatch:  # Bisa juga dipicu secara manual dari GitHub UI

jobs:
  fetch_video_urls:
    runs-on: ubuntu-latest  # Menjalankan di environment Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Menggunakan versi Python terbaru
      with:
        python-version: '3.9'  # Atur versi Python yang sesuai

    - name: Install dependencies
      run: |
        pip install yt-dlp  # Menginstal yt-dlp untuk mendownload video

    - name: Run video URL fetcher script
      env:
        YT_COOKIE: ${{ secrets.YT_COOKIE }}  # Cookie disimpan di GitHub Secrets
      run: |
        python3 your_script.py  # Ganti dengan nama skrip Python kamu
