name: Fetch MP4 URLs from YouTube

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Menjalankan setiap 6 jam

jobs:
  fetch-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Gunakan versi Python yang sesuai

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Install Dependencies (if any)
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify Files and Python Version
      run: |
        echo "Listing files in the current directory:"
        ls -al
        echo "Python version:"
        python --version

    - name: Run Python Script to Fetch MP4 URLs
      run: |
        python3 fetch_mp4_urls.py

    - name: Commit & Push URL Updates
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add public/output.txt
        git commit -m "Update MP4 URLs from yt-dlp" || echo "No changes"
        git push
