name: Video URL Fetcher

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam pada menit ke-0
  workflow_dispatch:  # Bisa juga dipicu secara manual dari GitHub UI

jobs:
  fetch_video_urls:
    runs-on: ubuntu-latest  # Menjalankan di environment Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout repository untuk mengakses file

    - name: Set up Python
      uses: actions/setup-python@v2  # Menggunakan Python versi 3.9
      with:
        python-version: '3.9'  # Versi Python yang akan digunakan

    - name: Install dependencies
      run: |
        pip install yt-dlp  # Menginstal yt-dlp untuk mendownload video
        pip install --upgrade gitpython  # Jika perlu untuk git push di skrip

    - name: Run video URL fetcher script
      env:
        YT_COOKIE: ${{ secrets.YT_COOKIE }}  # Cookie disimpan di GitHub Secrets
      run: |
        python3 fetch_mp4_urls.py  # Menjalankan skrip Python untuk mengambil video URL
